apiVersion: v2
name: vscode
description: Visual Studio Code is a lightweight yet powerful source code editor with a rich ecosystem of extensions for many languages.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
keywords:
  - IDE
  - Python
home: https://code.visualstudio.com/
sources:
  - https://github.com/InseeFrLab/vscode
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/vscode
  - https://github.com/cdr/code-server
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 6.8.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 2.6.0

dependencies:
  - name: library-chart
    version: 2.1.0
    repository: https://inseefrlab.github.io/helm-charts-datascience
