{{- if .Values.mongodb.discoverable.allow }}
{{- $fullname := include "library-chart.fullname" . }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "mongodb"
type: Opaque
data:
  mongodb-service: {{ (include "mongoList" .)  | b64enc | quote }}
  mongodb-name: {{ printf "%s" $fullname | b64enc | quote }}
  {{- if .Values.mongodb.auth.password  }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.password  }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.database  }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.rootPassword  }}
  mongodb-rootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  {{- end }}
  
{{- end -}}