ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

pinot:
  controller:
    name: controller
    replicaCount: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1G
      mountPath: /var/pinot/controller/data
      storageClass: ""
    external:
      #override
      enabled: false
      extra:
    extra:
      configs: "pinot.set.instance.id.to.hostname=true\ncontroller.task.scheduler.enabled=true\ncontroller.admin.access.control.factory.class=org.apache.pinot.controller.api.access.BasicAuthAccessControlFactory\ncontroller.admin.access.control.principals=admin\ncontroller.admin.access.control.principals.admin.password=verysecret"

#      configs: |-
#        pinot.set.instance.id.to.hostname=true
#        controller.task.scheduler.enabled=true
#        controller.admin.access.control.factory.class=org.apache.pinot.controller.api.access.BasicAuthAccessControlFactory
#        controller.admin.access.control.principals=admin
#        controller.admin.access.control.principals.admin.password=verysecret

  broker:
    name: broker
    replicaCount: 1
    external:
      #override
      enabled: false
    extra:
      configs: "pinot.set.instance.id.to.hostname=true\npinot.broker.access.control.class=org.apache.pinot.broker.broker.BasicAuthAccessControlFactory\npinot.broker.access.control.principals=admin\npinot.broker.access.control.principals.admin.password=verysecure"
#      configs: |-
#        pinot.set.instance.id.to.hostname=true
#        pinot.broker.access.control.class=org.apache.pinot.broker.broker.BasicAuthAccessControlFactory
#        pinot.broker.access.control.principals=admin
#        pinot.broker.access.control.principals.admin.password=verysecret
  server:
    name : server
    replicaCount: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4G
      mountPath: /var/pinot/server/data
      storageClass: ""
      #storageClass: "ssd"
  minion:
    name: minion
    replicaCount: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4G
      mountPath: /var/pinot/minion/data
      storageClass: ""
      #storageClass: "ssd
  zookeeper:
    enabled: true
    urlOverride: "my-zookeeper:2181/my-pinot"
    port: 2181
    replicaCount: 1
    persistence:
      enabled: true