apiVersion: v2
name: dask
description: Dask natively scales Python
icon: https://dask.org/_images/dask_icon_no_pad.svg
keyworks:
  - Python
  - Pandas
  - distributed
home: https://dask.org/
sources:
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/dask
  - https://github.com/dask/helm-chart
  - https://github.com/dask/dask

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1
dependencies:
  - name: dask
    version: 2021.9.1
    repository:  https://helm.dask.org/
    enabled: true




