apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-catalog
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{ $endpoint:= .Values.s3.endpoint }} 
{{ $namespace:= .Release.Namespace }}
{{ $hive:= .Values.discovery.hive }}
{{ $elastic:= .Values.discovery.elastic }}
{{ $mongodb:= .Values.discovery.mongodb }}
{{ $postgres:= .Values.discovery.postgres }}
{{ $username:= .Values.security.username }} 
{{ $password:= .Values.security.password }}
{{ range $index, $secret := (lookup "v1" "Secret" $namespace "").items }}
{{- if (index $secret "metadata" "annotations") }}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "mongodb" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "mongodb-service" | default "") | b64dec  }}
{{ $username:= ( index $secret.data "mongodb-username") | b64dec  }}
{{ $password:= ( index $secret.data "mongodb-password") | b64dec  }}
{{ $database:= ( index $secret.data "mongodb-database") | b64dec  }}
{{ $name:= ( index $secret.data "mongodb-name") | b64dec  }}
{{ $data := dict "mongodb" $mongodb "service" $service  "index" $index "username" $username "password" $password "database" $database "name" $name}}
{{- template "connector.mongodb2" $data -}}
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "postgres" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "postgres-service" | default "") | b64dec  }}
{{ $username:= ( index $secret.data "postgres-username") | b64dec  }}
{{ $password:= ( index $secret.data "postgres-password") | b64dec  }}
{{ $database:= ( index $secret.data "postgres-database") | b64dec  }}
{{ $port:= ( index $secret.data "postgres-port") }}
{{ $data := dict "postgres" $postgres "service" $service  "index" $index "username" $username "password" $password "database" $database "port" $port}}
{{- template "connector.postgres" $data -}}
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "hive" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "hive-service" | default "") | b64dec  }}
{{ $endpoint:= ( index $secret.data "hive-endpoint" | default "") | b64dec  }}
{{ $data := dict "hive" $hive "service" $service  "index" $index "endpoint" $endpoint }}
{{- template "connector.hive" $data -}}
{{- end -}}
{{- if and (index $secret "metadata" "annotations" "onyxia/discovery") (eq "elastic" (index $secret "metadata" "annotations" "onyxia/discovery" | toString)) }}
{{ $service:= ( index $secret.data "elastic-service" | default "") | b64dec  }}
{{ $port:= ( index $secret.data "elastic-port" | default "") | b64dec  }}
{{ $data := dict "elastic" $elastic "service" $service  "index" $index "port" $port }}
{{- template "connector.elastic" $data -}}
{{- end -}}
{{- end -}}
{{- end -}}   
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName | lower }}.properties: |
    {{- $relname :=  $catalogProperties | trim | split " " }}
    {{- range $prop := $relname }}
    {{-  $prop | nindent 4}}
    {{- end }}
{{- end }}