apiVersion: v2
name: mongodb
description: NoSQL document-oriented database that stores JSON-like documents with dynamic schemas, simplifying the integration of data in content-driven applications.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/mongodb.png
keywords:
  - nosql
  - Database
  - json
home: https://www.mongodb.com/
sources:
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/mongodb
  - https://github.com/bitnami/charts/tree/master/bitnami/mongodb
  - https://github.com/bitnami/bitnami-docker-mongodb
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1"
dependencies:
  - name: mongodb
    version: 12.1.21
    repository: https://charts.bitnami.com/bitnami
  - name: library-chart
    version: 2.0.20
    repository: https://inseefrlab.github.io/helm-charts-datascience
