apiVersion: v2
name: jena
description: Apache Jena Fuseki is a SPARQL server.
icon: https://jena.apache.org/images/jena-logo/jena-logo-jumbotron.png
keyworks:
  - RDF
  - Triplestore
  - Linked Data
home: https://jena.apache.org/jena
sources:
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/jena
  - https://github.com/stain/jena-docker
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: latest
