apiVersion: v2
name: argo-workflows
description: Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/argo.png
keyworks:
  - Worklow
  - Job
  - Task
home: https://argoproj.github.io/argo-workflows/
sources:
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/argo-workflows
  - https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1"
dependencies:
  - name: argo-workflows
    version: 0.15.0
    repository: https://argoproj.github.io/argo-helm
  - name: library-chart
    version: 2.0.20
    repository: https://inseefrlab.github.io/helm-charts-datascience
