ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  security:
    whitelist:
      enabled: true
      ip: "0.0.0.0/0"

argo-workflows:
  createAggregateRoles: false
  singleNamespace: true
  workflow:
    serviceAccount:
      create: true # Specifies whether a service account should be created
      annotations: {}
      name: "argo-workflows" # Service account which is used to run workflows
  controller:
    workflowNamespaces: []
    replicas: 1
    containerRuntimeExecutor: k8sapi
    clusterWorkflowTemplates:
      enabled: false

  server:
    enabled: true
    clusterWorkflowTemplates:
      enabled: false

    extraArgs:
      #- --auth-mode=sso
      - --auth-mode=server

    ingress:
      enabled: false